<a href="https://colab.research.google.com/github/Oh-Joshua/Forex_AnaliticsEntry_SimpleLinearRegression/blob/master/TutorialSimpleLenear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 単回帰分析の実装

傾き$a$の計算式
$$
a = \dfrac{\displaystyle{\sum_{n=1}^{N}}x_{n}y_{n}}
{\displaystyle{\sum_{n=1}^{N}}x_{n}^{2}}
$$

※ こういう科学技術式を記載することを、LaTeXという

In [0]:
import numpy as np
# 適当に数列を作る
x = np.array([1, 2, 3])
y = np.array([2, 3.9, 6.1])

In [0]:
x.mean()

2.0

In [0]:
y.mean()

4.0

In [0]:
# データを中心化する
xc = x - x.mean()

In [0]:
xc

array([-1.,  0.,  1.])

In [0]:
yc = y - y.mean()

In [0]:
yc

array([-2. , -0.1,  2.1])

In [0]:
# 要素ごとの掛け算（要素積）
xx = xc * xc

In [0]:
xy = xc * yc

In [0]:
xx

array([1., 0., 1.])

In [0]:
xy

array([ 2. , -0. ,  2.1])

In [21]:
xx.sum()

2.0

In [23]:
xy.sum()

4.1